name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-commit:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.check.outputs.match }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: check
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            TITLE="${{ github.event.pull_request.title }}"
          else
            TITLE=$(git log -1 --pretty=%B)
          fi
          if [[ $TITLE =~ ^(fix:|feat:|feat!:|BREAKING CHANGE:) ]]; then
            echo "match=true" >> "$GITHUB_OUTPUT"
          else
            echo "match=false" >> "$GITHUB_OUTPUT"
          fi

  release:
    needs: check-commit
    if: needs.check-commit.outputs.should_release == 'true'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # This ensures authentication with the token

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Configure git user
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'  # Use a generic email

      # Remove [skip ci] from the commit message if present
      - name: Remove [skip ci] from commit message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          # Remove the [skip ci] tag from the commit message
          NEW_COMMIT_MESSAGE=$(echo "$COMMIT_MESSAGE" | sed 's/\[skip ci\]//g')
          git commit --amend --no-edit -m "$NEW_COMMIT_MESSAGE"
          git push --force-with-lease

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
